### ISSUE TITLE
SM4 的 key 和 加解密字符串都必须是 16 位长度的吗？

### ISSUE THREAD

**Issue by mu-yu** [JuneAndGreen/sm-crypto#10]
测试发现 key 不是 16 位的长度直接会无法加解密, 待解加密字符串低于16位也无法加解密，大于16位仅加密16 位

测试代码：
```javascript
const sm4key = [0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10]
// const sm4OriginData = [0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10]
const sm4OriginData = 'abcdefghijklmnopqrstuvwxyz'.split('').map(x => x.charCodeAt(0))
let sm4EncData = sm4.encrypt(sm4OriginData, sm4key)
console.log(sm4EncData)

let sm4DecData = sm4.decrypt(sm4EncData, sm4key)
console.log(sm4DecData.map(x => String.fromCharCode(x)).join(''))
```
output: 
```
[
    5,  96, 145,
   84, 199, 170,
   36, 101, 198,
  106, 212,  61,
    8, 117, 167,
   14
]
abcdefghijklmnop
```

**Comment by yixianluo** [comment]
碰到类似问题，sm4是按16的倍数进行加密，有其他js实现跨越参考吗

**Comment by mu-yu** [comment]
@yixianluo 原始字符串可以是任意长度的，只不过要进行 padding/unpadding，这个库没有实现这一步而已。

还有这个可以参考下：
[sm-series-crypto](https://github.com/sickworm/sm-series-crypto)

**Comment by fancyboynet** [comment]
不知道作者有没有计划修复这个问题

**Comment by gy0801151351** [comment]
SM4对于key和iv的要求都是128位, 但是找了好多前端js的算法, 都把128位理解错了( 单纯的把128位换算成字符串的长度限制为16了, 其实是需要按字节位数换算. 比如base64格式和hex格式的key和iv, 需要先转换格式). 导致前端的sm4加密无法使用后端语言解密.

**Comment by mu-yu** [comment]
> SM4对于key和iv的要求都是128位, 但是找了好多前端js的算法, 都把128位理解错了( 单纯的把128位换算成字符串的长度限制为16了, 其实是需要按字节位数换算. 比如base64格式和hex格式的key和iv, 需要先转换格式). 导致前端的sm4加密无法使用后端语言解密.

无法解密可能是加密模式不同导致的，同样的 sm4,还分 cbc 和 ecb 等…

**Comment by JuneAndGreen** [comment]
key 要求 128 比特，加解密字符串在 0.2.0 版本支持了字符串输入和填充，详情可参考 README 或 testcase。
