### ISSUE TITLE
uniapp 提示未定义

### ISSUE THREAD

**Issue by OaimIsGnay** [JuneAndGreen/sm-crypto#107]
<img width="446" alt="image" src="https://github.com/JuneAndGreen/sm-crypto/assets/58240619/21328320-534c-4550-a081-419dc859767e">
<img width="996" alt="image" src="https://github.com/JuneAndGreen/sm-crypto/assets/58240619/f0b9066a-a910-4099-a579-59a839352a29">

**Comment by JuneAndGreen** [comment]
非 sm-crypto 相关问题，去对应第三方框架/库那边咨询下？

**Comment by OaimIsGnay** [comment]
> 非 sm-crypto 相关问题，去对应第三方框架/库那边咨询下？



> 非 sm-crypto 相关问题，去对应第三方框架/库那边咨询下？

大佬，就是考虑支持兼容uniapp吗？

**Comment by JuneAndGreen** [comment]
> 大佬，就是考虑支持兼容uniapp吗？

sm-crypto 就是个纯 js 库而已，最基础的接入方式已经提供了，不考虑为特定第三方做特别支持。

**Comment by OaimIsGnay** [comment]
> > 大佬，就是考虑支持兼容uniapp吗？
> 
> sm-crypto 就是个纯 js 库而已，最基础的接入方式已经提供了，不考虑为特定第三方做特别支持。

请问这个库支持vue3吗？
