### ISSUE TITLE
[feature request] SM4 需要支持 cbc 加解密模式

### ISSUE THREAD

**Issue by mu-yu** [JuneAndGreen/sm-crypto#11]
用 `bouncycastle` 实现的加解密（SM2/SM4-cbc）和本项目实现的加解密不兼容，互相无法解密另一方加密的内容。
目前的 SM4 加解密模式是 ecb 模式，实际上很多其他语言都是用cbc 模式来做…希望能支持cbc模式

**Comment by JuneAndGreen** [comment]
0.3.0 已支持
