### ISSUE TITLE
请问能支持国密csr生成吗？

### ISSUE THREAD

**Issue by Lazybin** [JuneAndGreen/sm-crypto#111]
现在用jsrsasign 生成不了

**Comment by emmansun** [comment]
既然用了jsrsasign，可以考虑使用基于jsrsasign的国密扩展实现啊。

**Comment by Lazybin** [comment]
> 既然用了jsrsasign，可以考虑使用基于jsrsasign的国密扩展实现啊。

我没有找到基于jsrsasign的国密扩展，请问大神有地址吗？

**Comment by emmansun** [comment]
> > 既然用了jsrsasign，可以考虑使用基于jsrsasign的国密扩展实现啊。
> 
> 我没有找到基于jsrsasign的国密扩展，请问大神有地址吗？

https://github.com/emmansun/sm2js

**Comment by Lazybin** [comment]
> > > 既然用了jsrsasign，可以考虑使用基于jsrsasign的国密扩展实现啊。
> > 
> > 
> > 我没有找到基于jsrsasign的国密扩展，请问大神有地址吗？
> 
> https://github.com/emmansun/sm2js

可以可以  66666
