### ISSUE TITLE
请教sm2.js的使用问题

### ISSUE THREAD

**Issue by lonycc** [JuneAndGreen/sm-crypto#122]
dist目录下有个sm2.js，通过`<script src="sm2.js"></script>`引入网页后，可以直接调用`sm2.doEncrypt`方法；
现在想通过node命令行运行sm2.js，试了在sm2.js新增一行 `console.log(sm2.doEncrypt(process.argv[2], process.argv[3]));`
然后命令行执行 `node sm2.js  aaaa 047df3e40511e1b88db0d62e9c02f937d1c691396842e7748d3664c34f35eb53d0deed1967624d1a2c84705a540f0502fface86873c4d045ee2607d04b361913de`，结果报错`sm2 is not defined`，请问问题出在哪里？

**Comment by JuneAndGreen** [comment]
nodejs 可以通过 commonjs / es module 的方式引入。
