### ISSUE TITLE
dist 中SM2随机出错，加密的数据 别的加密机或解密卡不能解密（自己加自己解没有问题，自己加的数据送到加密机不能解密  出错率 10%左右）一下抓取了一条出错数据：

### ISSUE THREAD

**Issue by wangjun796** [JuneAndGreen/sm-crypto#13]
dist 中SM2随机出错，加密的数据 别的加密机或解密卡不能解密（自己加自己解没有问题，自己加的数据送到加密机不能解密  出错率 10%左右）以下抓取了一条出错数据：
明文："11111111"
密文：1db3c72f5f0d012e2e56c6b92ea7f4081b49e2fd93e4a89c59cbe2dd028d8c8328d357b8e5e4e43ed395aa439d7fe032f92858ea0d53a02526a36eadb34faaa92ea1646f642f53812a4fc38876dbf253d38ea2ba4096d876462840b7b51c33b5719c09b08a170655
私钥：46D77D6E14C1DDC632159FA6E2AC3E204F6961869342DC99BC2684EDD71C57AB

_Originally posted by @wangjun796 in https://github.com/JuneAndGreen/sm-crypto/issues/1#issuecomment-529269755_

**Comment by wangjun796** [comment]
公钥：BB65BC1C454191D52B30312CDD9712E9C1EE993428C80CE070E69217892525F0F2DB9EE1779685EAB13F2E79F52582098863067D2043052E4C6727999A006E35

**Comment by gy0801151351** [comment]
可以参考#27中的办法试试看?

**Comment by JuneAndGreen** [comment]
可能是 leftPad 问题，已 fixed：https://github.com/JuneAndGreen/sm-crypto/commit/df2f016b59916165fe50a32b7f388e516cd5c827

试试 sm-crypto@0.2.1
