### ISSUE TITLE
SM2中的公私钥如何由pem文件中读取

### ISSUE THREAD

**Issue by liaokuan4hub** [JuneAndGreen/sm-crypto#14]
这里SM2是通过generateKeyPairHex()方法获取的公私钥，现需要使用别的语言生成的pem格式的公私钥，如何读取啊

**Comment by xiaohundun** [comment]
> 这里SM2是通过generateKeyPairHex()方法获取的公私钥，现需要使用别的语言生成的pem格式的公私钥，如何读取啊

。。。。为什么要专门读PEM，直接拿出来用不行么

**Comment by JuneAndGreen** [comment]
sm2 接口是支持传公钥私钥的，pem 格式解析不在加密算法里面，开发者可以自己解析，网上也有一些开源库有支持的。
