### ISSUE TITLE
我这边用证书签名加密对方解密失败

### ISSUE THREAD

**Issue by SKandAV** [JuneAndGreen/sm-crypto#17]
是有什么兼容问题需要注意吗

**Comment by JuneAndGreen** [comment]
可能是 leftPad 问题，已 fixed：https://github.com/JuneAndGreen/sm-crypto/commit/df2f016b59916165fe50a32b7f388e516cd5c827

试试 sm-crypto@0.2.1

**Comment by JuneAndGreen** [comment]
同 #27
