### ISSUE TITLE
前端加密后端不能每次都解密

### ISSUE THREAD

**Issue by hwenb** [JuneAndGreen/sm-crypto#19]
后端我用的bouncycastle，有时候生成的密钥能解开，有时候就解不开。

**Comment by aoldcat** [comment]
我也遇到了同样问题 @hwenb 你的解决了吗

**Comment by redfox105** [comment]
我们也遇到了同样的问题，js加密的密文，用bouncycastle的后台无法解密。

**Comment by gy0801151351** [comment]
解决办法参考 #27

**Comment by JuneAndGreen** [comment]
已 fixed：https://github.com/JuneAndGreen/sm-crypto/commit/df2f016b59916165fe50a32b7f388e516cd5c827

试试 sm-crypto@0.2.1

**Comment by JuneAndGreen** [comment]
同 #27
