### ISSUE TITLE
签名函数错误

### ISSUE THREAD

**Issue by lujun-wuhan** [JuneAndGreen/sm-crypto#2]
function doSignature(msg, privateKey, { pointPool, der, hash, publicKey } = {}) {
    let hashHex = typeof msg === 'string' ? _.parseUtf8StringToHex(msg) : _.parseArrayBufferToHex(msg);

    if (hash) {
        // sm3杂凑
        let publicKey = publicKey || getPublicKeyFromPrivateKey(privateKey);
        hashHex = doSm3Hash(hashHex, publicKey);
    }

修改为：

function doSignature(msg, privateKey, { pointPool, der, hash, publicKey } = {}) {
    let hashHex = typeof msg === 'string' ? _.parseUtf8StringToHex(msg) : _.parseArrayBufferToHex(msg);

    if (hash) {
        // sm3杂凑
        let pubKey= publicKey || getPublicKeyFromPrivateKey(privateKey);
        hashHex = doSm3Hash(hashHex, pubKey);
    }

**Comment by JuneAndGreen** [comment]
thx，已修复变量重新声明的问题。
