### ISSUE TITLE
SM2自己签名验签应该没啥问题，但是和别的语言是不通的

### ISSUE THREAD

**Issue by studentcaoqc** [JuneAndGreen/sm-crypto#20]
SM2自己签名验签应该没啥问题，但是和别的语言是不通的

**Comment by resyin** [comment]
+1

**Comment by JuneAndGreen** [comment]
看看是不是因为 userId 不同导致的，是的话，此位兄台的 pr 已支持：https://github.com/JuneAndGreen/sm-crypto/pull/18

**Comment by huahua315148** [comment]
+1

**Comment by JuneAndGreen** [comment]
试试 sm-crypto@0.2.1 可不可以？

**Comment by huahua315148** [comment]
您好作者，你的0.2.1版本刚刚试了，和java的验签还是没一样

**Comment by JuneAndGreen** [comment]
看看 sm3 杂凑、userId、asn.1 der 编码这几个可配置项是各端一致？

**Comment by lpilp** [comment]
> 
> 
> 您好作者，你的0.2.1版本刚刚试了，和java的验签还是没一样

我试了个python的可以的，可能是你在编码的问题，像python里要将签名转成bytes后再验证就对了，java在编码上问题可能会更大

**Comment by lpilp** [comment]
> 
> 看看 sm3 杂凑、userId、asn.1 der 编码这几个可配置项是各端一致？

sm3目录里的sm3对中文没有做utf8编码，但在sm2文件夹下的sm3是正确的，做了编码了，还有就是关于java端的问题，@huahua315148 ， 目前的java的版本基本基于BC库的，新版的1.66BC库已经可以和其他语言互通了，它默认的返回是 {der: true, hash: true} 这种的，验的时候带上这个参数就可以了

**Comment by lpilp** [comment]
@huahua315148 , 不好意思，测试不认真， java生成的用js可以通过，js生成的用java就通不过， 我用的  ZZMarquis /
gmhelper  封装的BC库，

**Comment by lpilp** [comment]
@huahua315148  在我家有一个 forhuahua的项目， 有相关的例子，可以java与js 互通了

**Comment by JuneAndGreen** [comment]
> > 看看 sm3 杂凑、userId、asn.1 der 编码这几个可配置项是各端一致？
> 
> sm3目录里的sm3对中文没有做utf8编码，但在sm2文件夹下的sm3是正确的，做了编码了，还有就是关于java端的问题，@huahua315148 ， 目前的java的版本基本基于BC库的，新版的1.66BC库已经可以和其他语言互通了，它默认的返回是 {der: true, hash: true} 这种的，验的时候带上这个参数就可以了

“sm3目录里的sm3对中文没有做utf8编码” --> 已支持

**Comment by 7-happy** [comment]
bouncycastle 版本：

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.61</version>
</dependency>
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcpkix-jdk15on</artifactId>
	<version>1.61</version>
</dependency>

java生成的签名，在js端可以正常验签（一定得加hash:true,der:true）：
let verifyResult = sm2.doVerifySignature(msgString, sigValueHex3, publicKey, {
    hash: true,
    der: true
}); // 验签为true
但是js端生成的签名（同样加了hash:true,der:true），在java端验签不过，java端自签自验也不过，再研究下了。。
