### ISSUE TITLE
ie浏览器不兼容

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [JuneAndGreen/sm-crypto#23]
ie不兼容

**Comment by JuneAndGreen** [comment]
ie 是不会考虑支持的了，太多东西没法用。

**Comment by Jean-Jacques-Nuoan** [comment]
希望能把通过webpack打包好的文件也上传到npm仓库里，我看install后的项目里面没有dist目录

**Comment by JuneAndGreen** [comment]
npm 上补充了，不过为了方便调试，npm 接入还是建议直接使用未构建版本。这个库构建与否并没有逻辑差异，也没有一些 debug 信息输出的插入，只是压缩混淆方面的差异而已。所以直接交由使用方进行构建也是一样的。

**Comment by LeoWang1991** [comment]
> ie 是不会考虑支持的了，太多东西没法用。

首先感觉大佬写这个库用哈，能否具体说一下，因为哪些东西没法用所以支持不了ie，领导现在要让我弄支持ie8的sm2加解密，因为我一开始以为这些算法都是js代码通过babel转成es3的以为是可以支持的。

是因为一些依赖的库一些语法不支持ie么？还望抽空赐教，非常感谢。我好和领导说下为啥不支持

**Comment by LeoWang1991** [comment]
https://blog.csdn.net/crazy_jialin/article/details/105950640 参考后面的，把cm-crypto中的sm2 sm3文件拿出来放到项目中，重新装下jsbn 自带的版本好像要低点，我这边用这个方法在ie8上解密没啥问题

**Comment by JuneAndGreen** [comment]
这个不敢确保，当时拿到 ie 跑过跑不通，再加上微软也准备放弃 ie，所以就不考虑了。

ie 的支持可能要开发者自己来尝试改造了，现在我这边想要搞一个真实 ie 的测试环境都困难，尤其是 ie8 这种更加老的 ie 版本。。。
