### ISSUE TITLE
生成的SM2密钥对的公钥为什么是130位的16进制数据？

### ISSUE THREAD

**Issue by 463010817** [JuneAndGreen/sm-crypto#24]
生成的SM2密钥对的公钥为什么是130位的16进制数据？不应该是128位的吗？

**Comment by JuneAndGreen** [comment]
看文档： https://github.com/JuneAndGreen/sm-crypto/tree/master/docs

![image](https://user-images.githubusercontent.com/7931744/85563217-c581fc00-b65f-11ea-9696-0e52ad91409c.png)
