### ISSUE TITLE
SM4怎么加密原始字符串？

### ISSUE THREAD

**Issue by fancyboynet** [JuneAndGreen/sm-crypto#26]
能给个demo吗，比如我想加密字符串"test"，要怎么做？谢谢

**Comment by JuneAndGreen** [comment]
给了一个最简单的例子：https://github.com/JuneAndGreen/sm-crypto/blob/master/test/sm4.test.js#L30

注意这里是以 16 个长度为一个单位来计算的，这里小于 16，就分配了 16 的长度；解密后需要还原回原本的长度。

**Comment by JuneAndGreen** [comment]
0.2.0 版本已直接支持。
