### ISSUE TITLE
前端sm2加密对接后端其他语言时有概率出现解密失败

### ISSUE THREAD

**Issue by gy0801151351** [JuneAndGreen/sm-crypto#27]
经过多方面测试, 发现js在处理数据时有可能出现数据位数对不上的BUG, 以下是经修改后的代码片段, 经测试可与java、C#、C++等其他语言正常对接10万次以上

var SM2Cipher = function () {
                function SM2Cipher() {
                    _classCallCheck(this, SM2Cipher);

                    this.ct = 1;
                    this.p2 = null;
                    this.sm3keybase = null;
                    this.sm3c3 = null;
                    this.key = new Array(32);
                    this.keyOff = 0;
                }

                
                SM2Cipher.prototype.GetHexString64 = function GetHexString64(h) {
                    if (h.length == 64) {
                        return h;
                    } else {
                        // console.log(h);
                        for (var i = h.length; i < 64; i++) {
                            h = "0" + h;
                        }
                        return h;
                    }
                },

                SM2Cipher.prototype.reset = function reset() {
                    this.sm3keybase = new SM3Digest();
                    this.sm3c3 = new SM3Digest();
                    // var xWords = _.hexToArray(this.p2.getX().toBigInteger().toRadix(16));
                    // var yWords = _.hexToArray(this.p2.getY().toBigInteger().toRadix(16));
                    var xWords = _.hexToArray(this.GetHexString64(this.p2.getX().toBigInteger().toRadix(16)));
                    var yWords = _.hexToArray(this.GetHexString64(this.p2.getY().toBigInteger().toRadix(16)));
                    // var xWords = this.GetWords(this.GetHexString64(this.p2.getX().toBigInteger().toRadix(16)));
                    // var yWords = this.GetWords(this.GetHexString64(this.p2.getY().toBigInteger().toRadix(16)));
                    this.sm3keybase.blockUpdate(xWords, 0, xWords.length);
                    this.sm3c3.blockUpdate(xWords, 0, xWords.length);
                    this.sm3keybase.blockUpdate(yWords, 0, yWords.length);
                    this.ct = 1;
                    this.nextKey();
                };

                SM2Cipher.prototype.doFinal = function doFinal(c3) {
                    // var yWords = _.hexToArray(this.p2.getY().toBigInteger().toRadix(16));
                    var yWords = _.hexToArray(this.GetHexString64(this.p2.getY().toBigInteger().toRadix(16)));
                    // var yWords = this.GetWords(this.GetHexString64(this.p2.getY().toBigInteger().toRadix(16)));
                    this.sm3c3.blockUpdate(yWords, 0, yWords.length);
                    this.sm3c3.doFinal(c3, 0);
                    this.reset();
                };

                SM2Cipher.prototype.nextKey = function nextKey() {
                    var sm3keycur = new SM3Digest(this.sm3keybase);
                    sm3keycur.update(this.ct >> 24 & 0x00ff);
                    sm3keycur.update(this.ct >> 16 & 0x00ff);
                    sm3keycur.update(this.ct >> 8 & 0x00ff);
                    sm3keycur.update(this.ct & 0x00ff);
                    sm3keycur.doFinal(this.key, 0);
                    for (var i = 0; i < this.key.length; i++) {
                        this.key[i] = this.key[i] & 255
                    }
                    this.keyOff = 0;
                    this.ct++;
                };

                SM2Cipher.prototype.initEncipher = function initEncipher(userKey) {
                    var keypair = _.generateKeyPairHex();
                    var k = new BigInteger(keypair.privateKey, 16);
                    var publicKey = keypair.publicKey;

                    this.p2 = userKey.multiply(k); // [k](Pb)
                    this.reset();

                    if (publicKey.length > 128) {
                        publicKey = publicKey.substr(publicKey.length - 128);
                    }

                    return publicKey;
                };

                SM2Cipher.prototype.encryptBlock = function encryptBlock(data) {
                    this.sm3c3.blockUpdate(data, 0, data.length);
                    for (var i = 0; i < data.length; i++) {
                        if (this.keyOff === this.key.length) {
                            this.nextKey();
                        }
                        data[i] ^= this.key[this.keyOff++] & 0xff;
                    }
                };

                SM2Cipher.prototype.initDecipher = function initDecipher(userD, c1) {
                    this.p2 = c1.multiply(userD);
                    this.reset();
                };

                SM2Cipher.prototype.decryptBlock = function decryptBlock(data) {
                    for (var i = 0; i < data.length; i++) {
                        if (this.keyOff === this.key.length) {
                            this.nextKey();
                        }
                        data[i] ^= this.key[this.keyOff++] & 0xff;
                    }
                    this.sm3c3.blockUpdate(data, 0, data.length);
                };

                SM2Cipher.prototype.createPoint = function createPoint(x, y) {
                    var publicKey = '04' + x + y;
                    var point = _.getGlobalCurve().decodePointHex(publicKey);
                    return point;
                };

                return SM2Cipher;
            }();

            module.exports = SM2Cipher;

            /***/
        })

**Comment by JuneAndGreen** [comment]
已 fixed：https://github.com/JuneAndGreen/sm-crypto/commit/df2f016b59916165fe50a32b7f388e516cd5c827

sm-crypto@0.2.1

**Comment by xiaopihaipanwei** [comment]
目前sm-crypto@0.3.12还是会出现几率性失败,查看前端加密结果和能正确解密结果比对,出现了位数缺失
后端是用java的hutool
