### ISSUE TITLE
请问作者有计划实现SM4的CBC模式吗?

### ISSUE THREAD

**Issue by gy0801151351** [JuneAndGreen/sm-crypto#28]
目前很多后端语言的SM4算法都已支持CBC模式, 比如: java的bouncycastle
期待作者支持一下SM4的CBC模式加解密

**Comment by l1t1** [comment]
https://github.com/wechat-miniprogram/sm-crypto/issues/8#issuecomment-698682862

**Comment by JuneAndGreen** [comment]
0.3.0 已支持
