### ISSUE TITLE
怎么通过 <script > 标签引入使用

### ISSUE THREAD

**Issue by Yangjia23** [JuneAndGreen/sm-crypto#3]

**Comment by JuneAndGreen** [comment]
有已经打包好做好压缩混淆的代码，可直接在 script 标签使用。会在 window 对象下挂上 sm2/sm3/sm4 对象。

[https://github.com/JuneAndGreen/sm-crypto/tree/master/dist](https://github.com/JuneAndGreen/sm-crypto/tree/master/dist)
