### ISSUE TITLE
sm2签名同一个字符串，每次得出来的结果都不一样，怎样设置可以让只要字符串和私钥相同得出来的签名都是一样的？

### ISSUE THREAD

**Issue by yangpeijia** [JuneAndGreen/sm-crypto#31]
待签名字符串：eyJraWQiOiIwMDEiLCJ0eXAiOiJKV1QiLCJhbGciOiJTTTIifQ.eyJleHAiOjE1NzQ5NjQ5MjMzMzgsImlhdCI6MTU3NDk2NDkyMTMzOCwianRpIjoiNmFkZmM2Y2UtMjZjYS00ZmRlLThmMDctM2QxMGFiNDA4ZGI2XzE1NzQ5NjQ5MjEzMzgifQ

私钥：f4e08d945183fc9fa6425561e4799efa8facfe0b715cb93c2db8a8142aad6f24

调用方法：sm2.doSignature(待签名字符串,私钥)

结果：

![image](https://user-images.githubusercontent.com/28385881/95670167-936aba80-0bba-11eb-82bd-10e74b96e070.png)

**Comment by yangpeijia** [comment]
里面的k值能不能通过传参设置成固定？

**Comment by undefine-man** [comment]
最近我在使用国密库发现，竟然同样的入参得出不一样的结果！而且解密后可以得出相同的数据，太神奇了

**Comment by changhr2013** [comment]
关联 https://github.com/dromara/hutool/issues/3491
