### ISSUE TITLE
angular2+和react 在ts环境下报错

### ISSUE THREAD

**Issue by austzyl** [JuneAndGreen/sm-crypto#32]
通过npm install @types/sm-crypto --save
安装成功，文件中也成功import，但是项目启动的时候报错：
Module not found: Error: Can't resolve 'sm-crypto' in 'D:\idea workspace\XXX\src\app'

angular 2+和react 项目都一样。

**Comment by JuneAndGreen** [comment]
未支持 ts，所以没有提供定义，目前请当成普通 js 库来处理吧。
