### ISSUE TITLE
有没有生成压缩公钥的算法

### ISSUE THREAD

**Issue by SinTan1071** [JuneAndGreen/sm-crypto#34]
如题，希望获取33位的压缩公钥，请问是否有办法提供

**Comment by JuneAndGreen** [comment]
此库是因为当时市面上基本没有前端可以用的国密库而诞生的，现在已经有比较多实现了，所以也基本不会再考虑添加新功能了。

如果有需要可参考文档来实现：https://github.com/JuneAndGreen/sm-crypto/blob/master/docs/SM2%E6%A4%AD%E5%9C%86%E6%9B%B2%E7%BA%BF%E5%85%AC%E9%92%A5%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95.pdf

**Comment by JuneAndGreen** [comment]
0.3.11 支持了压缩公钥。
