### ISSUE TITLE
webpack babel-polyfill 打包后ios10 （含ios10）以下系统不能使用

### ISSUE THREAD

**Issue by cam510** [JuneAndGreen/sm-crypto#4]
你好：
       请问一下webpack babel-polyfill 打包后ios10 （含ios10）以下系统不能使用，是我什么地方配置有误么？

**Comment by cam510** [comment]
补充一下使用react 框架

**Comment by JuneAndGreen** [comment]
有报错么？

**Comment by JuneAndGreen** [comment]
看起来是 `const { BigInteger } = xxxx` 这个结构赋值的语法在 ios 10不支持的样子，尝试调整一下 babel 的配置？

**Comment by cam510** [comment]
@JuneAndGreen 但是android5.1以下的也打不开，然后环境已经是es5了哦 T_T

**Comment by JuneAndGreen** [comment]
解构赋值是 es6 的规范。

**Comment by cam510** [comment]
@JuneAndGreen 
但好像使用babel-polyfill 环境已经是包含 es5 es6的哦，不是么？

**Comment by JuneAndGreen** [comment]
这个你得看 babel 的使用介绍，想要在低端环境上用，至少要转成 es5 的语法才行。es6 的语法在低端环境不一定支持。
