### ISSUE TITLE
sm4前后端没办法互相解密

### ISSUE THREAD

**Issue by SpaceCZ** [JuneAndGreen/sm-crypto#41]
sm2 前端去掉 04 后端加上 04 可以相互加解密，sm3 加密结果也是一致的。但是进行 sm4 加解密时候就出现没办法解密的问题，前端传给后端的代码后端解密不了，前端解后端的加密最后也输出的空......最后又找了一个 gm-crypto 解密的。请问这是什么原因啊 QAQ

**Comment by JuneAndGreen** [comment]
看看模式、填充方式等是否一样？

**Comment by SpaceCZ** [comment]
> 看看模式、填充方式等是否一样？

使用的 ECB 模式，问了一下后端，可能是由于 padding 模式不一致导致的吧......这个包里面关于padding的参数都有哪些啊，使用默认padding和none都没办法加解密.........

**Comment by SpaceCZ** [comment]
发现一个问题，包是默认使用 pkcs#5 填充的，如果我想换成 pkcs#7 填充的话是只能去改底层的代码么？还是说有配置接口？

**Comment by JuneAndGreen** [comment]
是的，目前 pkcs#7 还没支持，只支持了 pkcs#5

**Comment by SpaceCZ** [comment]
好的，了解了。谢谢
