### ISSUE TITLE
没有正常可以用的cdn链接吗？

### ISSUE THREAD

**Issue by cangyu1993** [JuneAndGreen/sm-crypto#43]
通过cdn网站查询到
`https://cdn.jsdelivr.net/npm/sm-crypto@0.3.0/src/index.min.js`
但是打开内部是引用，根本不能用，希望提供可用的cdn资源

**Comment by JuneAndGreen** [comment]
目前只处理代码的维护，不考虑投入到 cdn 等资源上。有需要的开发者可拿源码根据开源协议自行处理。

**Comment by JuneAndGreen** [comment]
npm 上的可以试试这个：https://unpkg.com/，应该管用
