### ISSUE TITLE
webpack 开启UglifyJsPlugin，打包时报错

### ISSUE THREAD

**Issue by citrusjunoss** [JuneAndGreen/sm-crypto#44]
ERROR in static-apph5/js/vendor.386ad02019772f8f622f.js from UglifyJs
Unexpected token name «i», expected punc «;» [./node_modules/sm-crypto/src/sm4/index.js:41,0][static-apph5/js/vendor.386ad02019772f8f622f.js:128191,11]

**Comment by citrusjunoss** [comment]
`JS
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
`

**Comment by citrusjunoss** [comment]
ERROR in static-apph5/js/vendor.221a66d29d2d27de6ffa.js from UglifyJs
 Name expected [./node_modules/sm-crypto/src/sm2/utils.js:2,0][static-apph5/js/vendor.221a66d29d2d27de6ffa.js:83099,6]

**Comment by citrusjunoss** [comment]
问题是UglifyJs 不支持ES6 语法。

**Comment by JuneAndGreen** [comment]
非源码问题，请开发者自行处理，如果要处理 es6，可以补个 babel 之类的，要么走 webpack 的 terser 插件。
