### ISSUE TITLE
SM3计算长文本或者大文件的时候效率比较低

### ISSUE THREAD

**Issue by tuibian** [JuneAndGreen/sm-crypto#45]
用sm3计算100kb的内容差不多要1秒多，这个怎么优化？

**Comment by JuneAndGreen** [comment]
你用的老版本吧，最近的几个版本重构过 sm3 实现，性能会比之前好。

比如这个测试用例，将近400k，我本地跑是 600ms 上下：https://github.com/JuneAndGreen/sm-crypto/blob/master/test/sm3.test.js#L40
