### ISSUE TITLE
SM2解密二进制数据？

### ISSUE THREAD

**Issue by blaesus** [JuneAndGreen/sm-crypto#50]
doDecrypt似乎期待解码出来的是utf8的数据，如果明文是二进制的，会报错` Malformed UTF-8 data`。
有办法开选项返回个Buffer、Uint8Array之类的吗，还是我应该直接改代码？

**Comment by JuneAndGreen** [comment]
0.3.6 版本已支持

**Comment by blaesus** [comment]
给力！
