### ISSUE TITLE
java加密，前端解密问题

### ISSUE THREAD

**Issue by diamond-tiger** [JuneAndGreen/sm-crypto#53]
sm-crypto:0.3.6
后端采用java 公钥进行sm2加密，前端使用私钥进行解密。
前端解密时，计算出c3与checkC3校验时因字母大小写，导致验证失败。无法解密。
前端js加解密无此问题。
应加上字符串转为小写，判断是否一致。
104行 
  if (checkC3 === c3) {   **#此处修改为  if (checkC3.toLowerCase()  === c3.toLowerCase() ) {**
    return output === 'array' ? msg : _.arrayToUtf8(msg)
  } else {
    return output === 'array' ? [] : ''
  }

![image](https://user-images.githubusercontent.com/28646133/141501795-5668661b-cfc7-42cb-ac30-fd41dba93dc9.png)

**Comment by JuneAndGreen** [comment]
c3 取自加密数据的一部分，看起来是你那边对加密数据做了大写处理。而 checkC3 中的字母来自 16 进制，是 js 的 toString 产出的，在标准之外此库是不会对数据做任何大小写调整的，需要业务层面自行处理此类问题。
