### ISSUE TITLE
SM2使用js引用，有时会报Cannot read properties of null (reading 'toBigInteger')

### ISSUE THREAD

**Issue by 790887413** [JuneAndGreen/sm-crypto#55]

**Comment by JuneAndGreen** [comment]
看看能不能给出具体的问题例子？

**Comment by 790887413** [comment]
import SM2 from '@src/utils/sm-crypto.js'

  const result1 = SM2.doEncrypt(msg + 'cs8', pubkeyHex, cipherMode)
  const result2 = SM2.doEncrypt(msg + 'cs8', pubkeyHex, cipherMode)
  const result3 = SM2.doEncrypt(msg + 'cs8', pubkeyHex, cipherMode)
  const result4 = SM2.doEncrypt(msg + 'cs8', pubkeyHex, cipherMode)
  const result5 = SM2.doEncrypt(msg + 'cs8', pubkeyHex, cipherMode)

这里上传不了图片，js里面在这一行报错了
 return n(t, [{
        key: 'getX',
        value: function () {
          return null === this.zinv && (this.zinv = this.z.modInverse(this.curve.q)), this.curve.fromBigInteger(this.x.toBigInteger().multiply(this.zinv).mod(this.curve.q));
        }
      }

**Comment by 790887413** [comment]
const SM2 = require('sm-crypto').sm2

**Comment by JuneAndGreen** [comment]
你的 pubkeyHex 是如何生成的？是不是出现问题时是 00 开头？如果是其他方式生成的 pubkeyHex，建议统一走未压缩的方式，也就是 04。

**Comment by 790887413** [comment]
pubkeyHex是04开头的，04D2F5D54201075C7E98734BFC1DB27*****

**Comment by JuneAndGreen** [comment]
看看有没有办法给出一个脱敏后的用例来？我这边确实复现不了。
