### ISSUE TITLE
IE11报错，导致白屏

### ISSUE THREAD

**Issue by wangerniu** [JuneAndGreen/sm-crypto#56]
bug描述
由于pkg.json中的main字段配置为src/index.js，导致生产环境引用未经过babel解析之后的包，导致线上业务白屏
原因定位
sm2/index.js下的代码未经编译，触发报错
```
const {BigInteger} = require('jsbn')
const {encodeDer, decodeDer} = require('./asn1')
```
![image](https://user-images.githubusercontent.com/15941949/150934940-f43c4b4d-d27a-43f8-8178-cfd70df7508f.png)
![image](https://user-images.githubusercontent.com/15941949/150934993-e7fd9d67-6847-475f-abc5-2df7ff5c22ee.png)

**Comment by JuneAndGreen** [comment]
本来就不考虑 IE 场景了。

如果想尝试 IE 下的话，可以试试直接使用 dist 下的包，dist 下的是构建给浏览器用的。或者直接使用 src 下的文件时手动过一下 babel。

**Comment by wangerniu** [comment]
好的，感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JuneAndGreen/sm-crypto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JuneAndGreen/sm-crypto] IE11报错，导致白屏 (Issue #56)





 
本来就不考虑 IE 场景了。
 
如果想尝试 IE 下的话，可以试试直接使用 dist 下的包，dist 下的是构建给浏览器用的。或者直接使用 src 下的文件时手动过一下 babel。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
