### ISSUE TITLE
靓仔你好, 好像没看到ecb模式, 我想拓展一下ecb模式,请问怎么拓展呢?

### ISSUE THREAD

**Issue by greenking19** [JuneAndGreen/sm-crypto#57]
如题

**Comment by JuneAndGreen** [comment]
sm4？sm4 应该默认就是 ecb：https://github.com/JuneAndGreen/sm-crypto/blob/master/src/sm4/index.js#L243

**Comment by greenking19** [comment]
> sm4？sm4 应该默认就是 ecb：https://github.com/JuneAndGreen/sm-crypto/blob/master/src/sm4/index.js#L243

好滴, 了解 谢谢靓仔!
