### ISSUE TITLE
SM4前端加密，后端解密报错

### ISSUE THREAD

**Issue by panzjcn** [JuneAndGreen/sm-crypto#59]
SM4-CBC 加密用得是java版的[sm-crypto]，其核心还是js版本。后端解密用得是Hutool。

请大咖调查看看是什么原因？

//1. 加密

        String msg = "hello";
        String key = "0123456789abcdeffedcba9876543210"; // 16 进制字符串，要求为 128 比特
        Sm4Options sm4Options4 = new Sm4Options();
        sm4Options4.setMode("cbc");
        sm4Options4.setIv("fedcba98765432100123456789abcdef");
        sm4Options4.setPadding("pkcs#5");
        // pkcs#5: db0669bd841e5450ec1652ecd42b6d60
        String encryptData4 = Sm4.encrypt(msg, key, sm4Options4); // 加密，cbc 模式，输出16进制字符串
        System.out.println("SM4 CBC加密：" + encryptData4);
        String decryptData8 = Sm4.decrypt(encryptData4, key, sm4Options4); // 解密，cbc 模式，输出 utf8 字符串
        System.out.println("SM4 CBC解密：" + decryptData8);

//1. 运行结果

    SM4 CBC加密：db0669bd841e5450ec1652ecd42b6d60
    SM4 CBC解密：hello

//2. 后端解密（Hutool）

        String content = "hello";
        String key1 = "0123456789abcdeffedcba9876543210";
        String iv1 = "fedcba98765432100123456789abcdef";
        byte[] key = HexUtil.decodeHex(key1);
        byte[] iv = HexUtil.decodeHex(iv1);
        SymmetricCrypto sm4 = new SM4(Mode.CBC, Padding.PKCS5Padding,key,iv);
        String encryptHex = "db0669bd841e5450ec1652ecd42b6d60";  //sm4.encryptHex(content);
        System.out.println(encryptHex);
        String decryptStr = sm4.decryptStr(encryptHex, CharsetUtil.CHARSET_UTF_8);
        System.out.println(decryptStr);

//2. 运行结果

    db0669bd841e5450ec1652ecd42b6d60
    Exception in thread "main" cn.hutool.crypto.CryptoException: BadPaddingException: pad block corrupted
	    at cn.hutool.crypto.symmetric.SymmetricCrypto.decrypt(SymmetricCrypto.java:331)
	    at cn.hutool.crypto.symmetric.SymmetricDecryptor.decrypt(SymmetricDecryptor.java:71)
	    at cn.hutool.crypto.symmetric.SymmetricDecryptor.decryptStr(SymmetricDecryptor.java:82)
	    at MyTest2.main(MyTest2.java:56)
    Caused by: javax.crypto.BadPaddingException: pad block corrupted
	    at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
	    at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	    at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	    at cn.hutool.crypto.symmetric.SymmetricCrypto.decrypt(SymmetricCrypto.java:329)
	    ... 3 more

**Comment by lpilp** [comment]
1 第一段的代码应该哪里有问题的，正确的加密出来应该是：7d440f460d870171c6cf966c9730a949
2 你用hutool加密下hello试试，加密出来是否一样
3 看这报错应该是补齐方式的问题的了，间接说明第一段的加解密代码是有问题的

**Comment by panzjcn** [comment]
> 1 第一段的代码应该哪里有问题的，正确的加密出来应该是：7d440f460d870171c6cf966c9730a949 2 你用hutool加密下hello试试，加密出来是否一样 3 看这报错应该是补齐方式的问题的了，间接说明第一段的加解密代码是有问题的

用hutool试了下是：7d440f460d870171c6cf966c9730a949

        String content = "hello";
        String key1 = "0123456789abcdeffedcba9876543210";
        String iv1 = "fedcba98765432100123456789abcdef";

        byte[] key = HexUtil.decodeHex(key1);
        byte[] iv = HexUtil.decodeHex(iv1);

        SymmetricCrypto sm4 = new SM4(Mode.CBC, Padding.PKCS5Padding,key,iv);
        String encryptHex = sm4.encryptHex(content);
        System.out.println(encryptHex);
        String decryptStr = sm4.decryptStr(encryptHex, CharsetUtil.CHARSET_UTF_8);
        System.out.println(decryptStr);

//运行结果

    7d440f460d870171c6cf966c9730a949
    hello

**Comment by panzjcn** [comment]
![image](https://user-images.githubusercontent.com/7620493/156341082-92fc8c72-1f58-48db-8c80-671a39cceab4.png)

java版的问题。
