### ISSUE TITLE
我参考你的算法写了一个dart包,已经开源. 方便放在你的你的README吗?

### ISSUE THREAD

**Issue by greenking19** [JuneAndGreen/sm-crypto#61]
在写flutter的时候需要到sm4,由于没有现成的自己写了一个
目前在dart pub跟github都开源了
dart版本的sm4. sm2跟sm3这两天完善
地址👉 [dart sm_scrpto](https://github.com/greenking19/sm_crypto.git)

**Comment by JuneAndGreen** [comment]
可以的，代码完成且测试用例完备后，可以这里回复我。
