### ISSUE TITLE
sm4 cbc模式解密失败，前端加密，后端解密

### ISSUE THREAD

**Issue by ustcck** [JuneAndGreen/sm-crypto#64]
前端：nodejs v14.18.1
npm install --save sm-crypto --registry=https://registry.npm.taobao.org
后端：java11
`<dependency>
    <groupId>com.antherd</groupId>
    <artifactId>sm-crypto</artifactId>
    <version>0.3.2</version>
</dependency>`

前端加密过程：
`D:\code-vue\test
λ node
Welcome to Node.js v14.18.1.
Type ".help" for more information.
> const sm4 = require('sm-crypto').sm4
undefined
> const msg = 'hello world! 我是 juneandgreen.'
undefined
> const key = '9a16ce945e03a9e816821e70cddbdb07'
undefined
> let encryptData = sm4.encrypt(msg, key, {mode: 'cbc', iv: 'fedcba98765432100123456789abcdef'})
undefined
> encryptData
'46acfa0b193e7709c9f0a902d77a542a1abb24e18c65a404379f2aff6f10042261a0845b4be8887142a8664a18ceb103'
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>`

后端解密过程：
   @Test
    void decrypt2() {
        String sm4Key = "9a16ce945e03a9e816821e70cddbdb07";
        String sm4Iv = "fedcba98765432100123456789abcdef";
        Sm4Options sm4Options4 = new Sm4Options();
        sm4Options4.setMode("cbc");
        sm4Options4.setIv(sm4Iv);
        String decryptDataForSm4 = Sm4.decrypt("46acfa0b193e7709c9f0a902d77a542a1abb24e18c65a404379f2aff6f10042261a0845b4be8887142a8664a18ceb103", sm4Key, sm4Options4);
        log.info("解密数据: {}", decryptDataForSm4);
    }

解密结果：
`13:34:18.561 [main] INFO com.*.cloud.auth.web.AuthControllerTest - 解密数据: ¹ր`

**Comment by lwmxiaobei** [comment]
我也一样···· java 解密失败

**Comment by lwmxiaobei** [comment]
而且 java 加密出来的是 base64

**Comment by lwmxiaobei** [comment]
> 我也一样···· java 解密失败

可以了，原来是iv不一样，这个两边要一致才行·····

**Comment by ustcck** [comment]
我iv两边一致的呀

**Comment by lwmxiaobei** [comment]
我加密可以···sm2 验 java 的签名不行·····

**Comment by changhr2013** [comment]
@ustcck 可以使用 hutool 的 SM4/CBC/PKCS5Padding：
```java
String sm4Key = "9a16ce945e03a9e816821e70cddbdb07";
String sm4Iv = "fedcba98765432100123456789abcdef";
String encrypted = "46acfa0b193e7709c9f0a902d77a542a1abb24e18c65a404379f2aff6f10042261a0845b4be8887142a8664a18ceb103";
SM4 sm4 = new SM4(Mode.CBC, Padding.PKCS5Padding, Hex.decode(sm4Key), Hex.decode(sm4Iv));
byte[] decrypt = sm4.decrypt(Hex.decode(encrypted));
System.out.println(new String(decrypt, StandardCharsets.UTF_8));
```

```text
hello world! 我是 juneandgreen.
```

**Comment by changhr2013** [comment]
@lwmxiaobei 签名看看是不是编码问题，大部分都是 DER 编码导致的。

**Comment by ustcck** [comment]
> @ustcck 可以使用 hutool 的 SM4/CBC/PKCS5Padding：
> 
> ```java
> String sm4Key = "9a16ce945e03a9e816821e70cddbdb07";
> String sm4Iv = "fedcba98765432100123456789abcdef";
> String encrypted = "46acfa0b193e7709c9f0a902d77a542a1abb24e18c65a404379f2aff6f10042261a0845b4be8887142a8664a18ceb103";
> SM4 sm4 = new SM4(Mode.CBC, Padding.PKCS5Padding, Hex.decode(sm4Key), Hex.decode(sm4Iv));
> byte[] decrypt = sm4.decrypt(Hex.decode(encrypted));
> System.out.println(new String(decrypt, StandardCharsets.UTF_8));
> ```
> 
> ```
> hello world! 我是 juneandgreen.
> ```
> 
> Java 有自己的算法库，实在没必要去调用 js，性能低，扩展性还受限。

可以，十分感谢

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 签名看看是不是编码问题，大部分都是 DER 编码导致的。

具体要看哪里呢？

**Comment by changhr2013** [comment]
@lwmxiaobei 看你的签名是不是 ASN1 格式的，可以提供一个出来看看。

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 看你的签名是不是 ASN1 格式的，可以提供一个出来看看。

MEUCIQCsgk0rDZd2eLJ3R50Eyp4QQWdtrXlDh+gkBPmxWQ2OGwIgbmROVeS0E9w6Eh2hxmPTNMCL/8XvQ9CsLP6oXIDjc+Y=

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 看你的签名是不是 ASN1 格式的，可以提供一个出来看看。

这个 304402205db9d619cfdf7f13a013b49056bae6a1131065ada77a95144c8af862791b161302200fdf03407e5dd6085e38a0755bd5a7b5149b03336d411597daf13224e7d84d0c

**Comment by changhr2013** [comment]
@lwmxiaobei 看着是带 DER 编码的，使用：
```js
let verifyResult3 = sm2.doVerifySignature(msg, sigValueHex3, publicKey, {
    der: true,
});
```
如果不行，可以把 hash 也设置成 true 试试：
```js
let verifyResult3 = sm2.doVerifySignature(msg, sigValueHex3, publicKey, {
    der: true,
    hash: true
});
```

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 看着是带 DER 编码的，使用：
> 
> ```js
> let verifyResult3 = sm2.doVerifySignature(msg, sigValueHex3, publicKey, {
>     der: true,
> });
> ```
> 
> 如果不行，可以把 hash 也设置成 true 试试：
> 
> ```js
> let verifyResult3 = sm2.doVerifySignature(msg, sigValueHex3, publicKey, {
>     der: true,
>     hash: true
> });
> ```

也是 true的, 已下是我的代码
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16284775/164389767-7431d45e-d90a-4654-af4b-dcf52bb26ad5.png">

**Comment by changhr2013** [comment]
@lwmxiaobei 你的 js 和 java 各语言自签自验能过去吗？我怎么发现这个调用 js 的 java 库自签自验过不去。

**Comment by lwmxiaobei** [comment]
> 

我用 js 的库自签自验是可以的，我对接方是 java 的验证失败

**Comment by changhr2013** [comment]
@lwmxiaobei 你 userId 设置的是多少?

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 你 userId 设置的是多少?

16 位的 utf8 字符串

**Comment by changhr2013** [comment]
@lwmxiaobei 设置成 1234567812345678，很多库默认的用的是推荐参数。

**Comment by changhr2013** [comment]
目前来看 hutool 是能过的：
```java
// 生成公私钥对
Keypair keypair = Sm2.generateKeyPairHex();
String privateKey = keypair.getPrivateKey();
String publicKey = keypair.getPublicKey();

SignatureOptions options = new SignatureOptions();
options.setDer(true);
options.setHash(true);
options.setUserId("1234567812345678");

// 使用包装了 js 的 java 库签名
String s = Sm2.doSignature("123", privateKey, options);
System.out.println(s);

// 使用 hutool 库验签
SM2 sm2 = new SM2(privateKey, publicKey);
boolean verify = sm2.verify("123".getBytes(StandardCharsets.UTF_8), Hex.decode(s));
System.out.println(verify);
```

```text
3044022014c7cdb2a6857d6c822482757548c2ea3f68d11c6084f3a4da1c9ec6e03361c202202f8068be654145d4d6a016d698a04986f3a98f54d38585146f726caa6afec4c7
true
```

**Comment by lwmxiaobei** [comment]
> @lwmxiaobei 设置成 1234567812345678，很多库默认的用的是推荐参数。

这个不需要和我对接方一样吗？我现在用的和 java 那边约定好的

**Comment by changhr2013** [comment]
@lwmxiaobei 你 java 那边用的哪个库，包装了 js 的库吗？

**Comment by lwmxiaobei** [comment]
> 1234567812345678

应该不是
import org.bouncycastle.asn1.ASN1EncodableVector;
import org.bouncycastle.asn1.ASN1InputStream;
import org.bouncycastle.asn1.ASN1Integer;
import org.bouncycastle.asn1.ASN1Sequence;
import org.bouncycastle.asn1.DERSequence;
import org.bouncycastle.crypto.params.ECDomainParameters;
import org.bouncycastle.crypto.params.ECPrivateKeyParameters;
import org.bouncycastle.crypto.params.ECPublicKeyParameters;
import org.bouncycastle.crypto.params.ParametersWithID;
import org.bouncycastle.crypto.signers.SM2Signer;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.jce.spec.ECParameterSpec;
import org.bouncycastle.math.ec.ECPoint;

**Comment by changhr2013** [comment]
用的 bc 库，hutool 封装的就是 bc 库，我测试了下，是可以互认的，让你们 java 那边排查下吧，测试时最好统一使用国密的推荐参数，调试通过后再统一改参数。

**Comment by lwmxiaobei** [comment]
他们是银行那边····应该不会错吧，而且奇怪的是，他们加签的我 js 可以验签，但是 js 加签的他们就验不了

**Comment by changhr2013** [comment]
> 他们是银行那边····应该不会错吧，而且奇怪的是，他们加签的我 js 可以验签，但是 js 加签的他们就验不了

除非能知道他们的验签逻辑，要不然不好排查，大部分情况下都是参数设置和编码问题。

**Comment by changhr2013** [comment]
方便提供下他们那边的原文，签名、公钥、userId 吗，我可以帮你把各种验签组合试一下 😂

**Comment by ustcck** [comment]
> 目前来看 hutool 是能过的：
> 
> ```java
> // 生成公私钥对
> Keypair keypair = Sm2.generateKeyPairHex();
> String privateKey = keypair.getPrivateKey();
> String publicKey = keypair.getPublicKey();
> 
> SignatureOptions options = new SignatureOptions();
> options.setDer(true);
> options.setHash(true);
> options.setUserId("1234567812345678");
> 
> // 使用包装了 js 的 java 库签名
> String s = Sm2.doSignature("123", privateKey, options);
> System.out.println(s);
> 
> // 使用 hutool 库验签
> SM2 sm2 = new SM2(privateKey, publicKey);
> boolean verify = sm2.verify("123".getBytes(StandardCharsets.UTF_8), Hex.decode(s));
> System.out.println(verify);
> ```
> 
> ```
> 3044022014c7cdb2a6857d6c822482757548c2ea3f68d11c6084f3a4da1c9ec6e03361c202202f8068be654145d4d6a016d698a04986f3a98f54d38585146f726caa6afec4c7
> true
> ```

@lwmxiaobei 刚刚试了，前端sm-crypto签名，后端hutool验签，是ok的

前端：
`sign = sm2.doSignature('123', privateKey, {
    der: true,
    hash: true
})`

后端：
`SM2 sm2 = new SM2(sm2WebPrivateKey, sm2WebPublicKey);
        boolean verify = sm2.verify("123".getBytes(StandardCharsets.UTF_8), Hex.decode(sign ));

        log.info("verify: {}", verify);`

**Comment by lwmxiaobei** [comment]
> 

userid 加上也是可以的吗？

**Comment by changhr2013** [comment]
userId 只是为了做 SM2 的预处理，参与计算 Z，看源码，没有传入 userId 的话，默认会使用 `1234567812345678`，传不传都一样的。

**Comment by changhr2013** [comment]
改成 `abcdefg` 只要对上也是一定能过的：
```java
// 生成公私钥对
Keypair keypair = Sm2.generateKeyPairHex();
String privateKey = keypair.getPrivateKey();
String publicKey = keypair.getPublicKey();

SignatureOptions options = new SignatureOptions();
options.setDer(true);
options.setHash(true);
options.setUserId("abcdefg");

// js 签名
String s = Sm2.doSignature("123", privateKey, options);
System.out.println(s);

// hutool 验签
SM2 sm2 = new SM2(privateKey, publicKey);
boolean verify = sm2.verify("123".getBytes(StandardCharsets.UTF_8), Hex.decode(s), "abcdefg".getBytes(StandardCharsets.UTF_8));
System.out.println(verify);

// hutool 签名
byte[] sign = sm2.sign("123".getBytes(StandardCharsets.UTF_8), "abcdefg".getBytes(StandardCharsets.UTF_8));
System.out.println(Hex.toHexString(sign));

// js 验签
boolean b = Sm2.doVerifySignature("123", Hex.toHexString(sign), publicKey, options);
System.out.println(b);
```

```text
3045022070cb0f15f796f18c6f870bb9d0a1a7e14a21756f5aae4a809a6f8548f56706d1022100c5a27e5818b6a23a436b0e38d54e1c646db6160c3cfe172fe018844c400b2915
true
3045022100f91e14f9e9bfac46e1a1c581134fd369519aabe76364bf6785666d5806b0830d02200cfa088bad0cd6c86db33e6bb1d6899d3dc03103599e37f5b64444be2b417e53
true
```

**Comment by ustcck** [comment]
前端sm-crypto默认 userId 值为 1234567812345678
