### ISSUE TITLE
sm2加密报错

### ISSUE THREAD

**Issue by qiuf2004** [JuneAndGreen/sm-crypto#68]
import { sm2 } from 'sm-crypto';
sm2.doEncrypt(oldPassword, publicKey, 1)
报错如下：
![image](https://user-images.githubusercontent.com/51955656/175913899-6143a720-d3f7-4b28-9a60-679b6dee05af.png)

**Comment by qiuf2004** [comment]
后端生成的publicKey,前端加密报错

**Comment by qiuf2004** [comment]
公钥转成点的时候，publicKey是null

**Comment by changhr2013** [comment]
给一组测试数据看看，一般是数据格式问题@qiuf2004

**Comment by qiuf2004** [comment]
公钥

MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEX4c8xiFxa0tY8duNI6d2v9el/Vo/wWiOZoR3BZvJF+9t8ema2m+9Swj7PoFuy//i97WMfyVAKBsAIiG/rgnupA==

**Comment by changhr2013** [comment]
@qiuf2004 你好，看你给的公钥是经过 ASN1 编码的格式，这个 js 库目前公钥的格式只支持原始未编码的公钥，建议你们后端对公钥做一下处理，传递原始公钥给你用，例如上面你给出的公钥，DER 解码后，得到 X、Y 点，添加压缩标识位，编码为 Hex 格式为：
```js
045f873cc621716b4b58f1db8d23a776bfd7a5fd5a3fc1688e668477059bc917ef6df1e99ada6fbd4b08fb3e816ecbffe2f7b58c7f2540281b002221bfae09eea4
```

**Comment by qiuf2004** [comment]
请教下：DER 解码，添加压缩标识位怎么实现的




像风一样的飞去
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JuneAndGreen/sm-crypto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JuneAndGreen/sm-crypto] sm2加密报错 (Issue #68)





 
@qiuf2004 你好，看你给的公钥是经过 ASN1 编码的格式，这个 js 库目前公钥的格式只支持原始未编码的公钥，建议你们后端对公钥做一下处理，传递原始公钥给你用，例如上面你给出的公钥，DER 解码后，得到 X、Y 点，添加压缩标识位，编码为 Hex 格式为：
 045f873cc621716b4b58f1db8d23a776bfd7a5fd5a3fc1688e668477059bc917ef6df1e99ada6fbd4b08fb3e816ecbffe2f7b58c7f2540281b002221bfae09eea4
