### ISSUE TITLE
sm4

### ISSUE THREAD

**Issue by peachapp** [JuneAndGreen/sm-crypto#69]
sm4.encrypt(msg, key) 这是哪种模式啊

**Comment by changhr2013** [comment]
默认走 ECB/Pkcs7Padding 模式

**Comment by peachapp** [comment]
> 默认走 ECB/Pkcs7Padding 模式
好谢谢，这个用的是utf-8吗

**Comment by changhr2013** [comment]
@peachapp 入参统一编成 hex 格式，按 readme 的说明来。

**Comment by JuneAndGreen** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/7931744/176340662-38d9d8b5-dbcd-4df4-893c-3b8d09349cbf.png">
默认 ecb，可选 cbc
