### ISSUE TITLE
有方法能从文件中获取私钥和公钥吗

### ISSUE THREAD

**Issue by hadibu** [JuneAndGreen/sm-crypto#7]
现在看说明公钥和私钥是通过generateKeyPairHex生成的，有办法从pem文件或者p12之类的文件中读取到吗？

**Comment by JuneAndGreen** [comment]
本库只提供纯粹的加解密/hash/签名/验签，且前端/nodejs通用。解析 pem 文件等和特定场景有关的逻辑本库不考虑支持，可使用一些特定场景的开源库解决。
