### ISSUE TITLE
java版本的0.3.2版本，和js版本的0.3.8版本，无法互相签名验签

### ISSUE THREAD

**Issue by xezBachelor** [JuneAndGreen/sm-crypto#73]
publickey: 044310f0521b99a95fcb0a44f21fb0a77e9bda35516eb42208fc3a576ebc8cae93fa94834e22060abd8528483bad0ee010bda0bb32ef111bd8773a91aeb517f8db
privatekey: 00d243de79a2741a3b37cc978add7ff39d7ac0d7c7f24ebadd95f3c3c071d4d5cd

原始串: 1234567890
java版本签名：3044022010ba478cbc88d381b9f9e645e6572ae50878f2ce46eccfcfff753ef7231b834502204511da8360a98384294c3e8893ea2276e18ccc0b954c50671ade8c613a2091b2
js版本验签不通过

bc版本java签名：304602210089d4f88e39ddbd9308a815b9d02aa2190c21a836126f881458d140db486a32a9022100a01db5715825d050ffef9a42121c6ab72a46db0e43004cce5383f1b12a40bb72
js版本验签可以通过

**Comment by JuneAndGreen** [comment]
java 版本问题请在 https://github.com/antherd/sm-crypto/ 中提 issue，不过应该让作者更新下 resources 应该就可以了。
