### ISSUE TITLE
sm3获取json串的hash，前后端生成不一样，而且都和在线生成的不一样

### ISSUE THREAD

**Issue by 596094101** [JuneAndGreen/sm-crypto#74]
json串生成有啥坑吗是

**Comment by JuneAndGreen** [comment]
如果用普通字符串或者字节数组跑各端 sm3，结果一样不？此库的 sm3 是按照此文档实现的，正常通过了其中的用例，可以看看其他端是否也符合预期。

**Comment by huangyuefeng666** [comment]
大佬sm3的hmac是不是只能传普通字符串或者字节数组
