### ISSUE TITLE
SM4 获取到的 key 为 33 位，该如何处理后使用？

### ISSUE THREAD

**Issue by a77uu** [JuneAndGreen/sm-crypto#78]
密文、key 以及 iv 于在线工具中可正常解密。在线工具设置如下：

![image](https://user-images.githubusercontent.com/45524688/201032995-4b3295fa-d333-4a1a-b5c0-8b2c9dcb99c0.png)

该如何在这个库中实现？因为 key 标准来讲是 32 位；

**Comment by a77uu** [comment]
密文：
`2ZFJ12Ju+3AKiZnyZJLS175M4Mnv2tVTptDPdkf5LaP1MwriSP5pnlD81jt+d86fXOfigq2HPMeNnDERX8V7iIX6tVRSaD0MqS0aTaMNo3UNy08xY0kiSXqeuckwAgg+GOzG0QdBWHZLaEvk5gWR5iIuVXc9aK1b6QhQGP+4WMrjKhApY1gSBKsMg9UPlU/EQ7izyY7m9UANwUb0PHDDTXK357ujnuZrhA17MUSXhwg=`

Key：
`111101525715018487214501319884958`

IV：
`1111015219884958`

Result：
`{"code":1, "message":"成功", "data":{
  "srvrt": {
    "timeStamp": "1668066248909",
    "resultCode": "0300",
    "resultMessage": "文件ID（fileId）不能为空"
  }
}}`

**Comment by JuneAndGreen** [comment]
https://github.com/JuneAndGreen/sm-crypto/blob/master/docs/SM4%E5%88%86%E7%BB%84%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95.pdf

此库只按标准文档实现，要求输入密钥为 128 比特，但是密钥本身不是由此库生成，你按自己业务的需求将其调整到 128 比特即可。
