### ISSUE TITLE
加解后的密文如何支持asn1/der编码格式，大佬有示例吗？

### ISSUE THREAD

**Issue by ielgnaw** [JuneAndGreen/sm-crypto#82]
加解后的密文如何支持asn1/der编码格式，大佬有示例吗？
@JuneAndGreen

**Comment by JuneAndGreen** [comment]
参考签名/验签处理：

https://github.com/JuneAndGreen/sm-crypto/blob/d9ae8b1bbffbdeb580824e3591b600168d2f0722/src/sm2/index.js#L151
https://github.com/JuneAndGreen/sm-crypto/blob/d9ae8b1bbffbdeb580824e3591b600168d2f0722/src/sm2/index.js#L169
