### ISSUE TITLE
sm2的规范中，密文前应该有04标识对吗，为什么这个库没有呢

### ISSUE THREAD

**Issue by dora0077** [JuneAndGreen/sm-crypto#86]
同样如果后端的密文带有04，前端也解密不了，请问是因为什么考虑在这个库中不处理04标识啊

**Comment by JuneAndGreen** [comment]
有 04 开头是因为 c1 本质上和公钥差不多，即 04 + x + y 的格式

<img width="781" alt="image" src="https://user-images.githubusercontent.com/7931744/231943671-da077f53-ee8f-499f-bc8f-2568381a859b.png">

最开始这个库未开源时并不支持其它类型公钥（包括压缩公钥），所以为了兼容某些场景统一去掉了 04 来处理，而后开源时沿用了这个实现：

<img width="964" alt="image" src="https://user-images.githubusercontent.com/7931744/231944673-252bfe76-b98f-474c-9cc2-c82ec58d5aa3.png">

有需要可以手动补充

**Comment by JuneAndGreen** [comment]
解密时同理：
<img width="809" alt="image" src="https://user-images.githubusercontent.com/7931744/231945070-3e40a0c4-db4a-47d8-a53c-64a68e48963a.png">

**Comment by dora0077** [comment]
明白了，感谢！

**Comment by changhr2013** [comment]
关联一下相关资料：
[Elliptic Curve Cryptography Subject Public Key Information - 2.2 Subject Public Key](https://www.rfc-editor.org/rfc/rfc5480#section-2.2)
[SEC 1: Elliptic Curve Cryptography](https://www.secg.org/sec1-v2.pdf)
