### ISSUE TITLE
js加密,服务端(java hutool)解密,概率性出现解密失败

### ISSUE THREAD

**Issue by xiaopihaipanwei** [JuneAndGreen/sm-crypto#87]
前端
> @0.3.12 

后端

> hutool 5.8.15
> bcprov-jdk15on 1.70

私钥 

> f4320510c51fda88e6d1cc94b72bb2b87937d029a143e6530b47e36104f8cbeba

公钥 

> 046f4faad8636064768ae92dc692ccb299f47fe284698a42c1ce76bb5cd75cc2b621dd3dc2dea0db2ba6ccfe53fcf8f0f12c11cb4437438e2fdc02ca417ad10b5c

无法解密密文(258):

> 044ebf6602a087663627c4efadb0622fb043e46e37c546e03791c528b26641c2568b048c687f275cd4e4523b3363e15cb4d1a6cd015ee4ba40e617f4aa7a7a78fcd6635906b0962ae3197954c2963de5b9b818550840c30c850ae8eac8dedf2676c1ba24b63b13973b7b97e0d63fb43c9e865418f5470b548552b14a8dd9d6277e

正常可解密密文(260)

> 04fd34cbba3fc080d686255d7c57d927e229304ea918c0178726d168e1eafd4b76a948da2ac69983d0b97eb3a4dc7a8be81112a3cef566b8a98d8dac971d481512e76a503c257e0dea1b5a836ffb367b111795a7a324aff3474cb9f162057304b3410f3a496bf09fc5a566e6dfc26999806a431aa59e14fcda67eddd22e02fb53c30

看之前的issues也是存在位数不对服务端无法解密

![image](https://github.com/JuneAndGreen/sm-crypto/assets/18275611/781266c3-27d9-49f9-af51-3f23b58b094c)

new error 是后端生成的公私钥
old error 是前端生成的公私钥

**Comment by zcong2333** [comment]
我目前查到sm2加密结果是C1X+C1Y+C3+C2,其中C1X,C1Y说是32字节，但也可能少于32字节的情况，位数少了估计是这个问题，服务端解密也不知道怎么改,java一般是基于bouncycastle这个库，也不知道有没有新的可以兼容。基于openssl的话，https://xie.infoq.cn/article/9685264098848c3024593c629可以看看这个，升级一下版本，我也还没验证

**Comment by changhr2013** [comment]
@xiaopihaipanwei 我运行了 1 万次加密，复现不了位数不对的情况，如果有能复现的代码麻烦贴一下看看。

**Comment by xiaopihaipanwei** [comment]
@changhr2013 

前端代码

```
const sm2 = require("sm-crypto").sm2;

const bizData = sm2.doEncrypt("12345abc", this.publicKey1, 1);
````
正常密文(210)

> 04604f47a1393186d19047844f8efef837bea2339787b27daf58d10154dda3f1793a0b12906f9e62e189a0dc322d8d7ad2b8d2838cc14fd184135755c4b1f69ab401b31b0645489f8909823ad6cdd1b38aef97ad5c5ee17794f8d8a844509e056717be25653427d00f

无法解密密文(208)

> 044fafb9e39172c9268f4cf37e24dc47a0be6f1ebf17295f479dd8afd477adeeffd65f97de271997815a4bd5d656991104a12638e727ff10a9c7a51d3c375b6178203b096f98f058203af720fa1e7844d475a1dee433ee14b5eab508939842290a18e239aa5886bb

**Comment by xiaopihaipanwei** [comment]
@changhr2013 不好意思 刚刚和前端比对了一下,发现是有概率出现加密原文开头是04的情况,所以后端判断没有加上04导致无法解密. 麻烦大佬了
