### ISSUE TITLE
sm2签名 支持r 和 s输出吗

### ISSUE THREAD

**Issue by arelinaa** [JuneAndGreen/sm-crypto#88]
类似于这种
![image](https://github.com/JuneAndGreen/sm-crypto/assets/106329934/6bfcfa1e-4052-41cb-9d54-395e6c21e34c)

**Comment by JuneAndGreen** [comment]
<img width="784" alt="image" src="https://github.com/JuneAndGreen/sm-crypto/assets/7931744/1f6bf24d-9ff3-4cfe-aeaf-71430e8a2fe9">

去掉 der 编码，你就能拿到 r 和 s 了
