### ISSUE TITLE
vue项目，计算视频文件SM3，大一点的就崩溃

### ISSUE THREAD

**Issue by wenheyu** [JuneAndGreen/sm-crypto#97]
目前前端测试20M左右的正常，但是计算有点慢，如果是200M以上的页面就崩溃了，是否可以支持分块计算

**Comment by JuneAndGreen** [comment]
试下这个同学的优化实现？

https://github.com/Cubelrti/sm-crypto-v2

**Comment by wenheyu** [comment]
> ### Reference in new issue

这个库跑不起来，会报错。我看介绍基本针对字符串的，没有提到文件相关的

**Comment by wenheyu** [comment]
> 试下这个同学的优化实现？
> 
> https://github.com/Cubelrti/sm-crypto-v2

这个库反而跑不起来，我看介绍，没有文件相关的

**Comment by wenheyu** [comment]
我在import就已经报错了，应该是不兼容的问题吧

**Comment by JuneAndGreen** [comment]
只要你不是过于老旧的浏览器，那么按道理跟我这边的实现没有差太多的，只是他那边是用 ts 编写的，且做了些优化工作。

**Comment by JuneAndGreen** [comment]
> 我在import就已经报错了，应该是不兼容的问题吧

只要你不是过于老旧的浏览器，那么按道理跟我这边的实现没有差太多的，只是他那边是用 ts 编写的，且做了些优化工作。
