### ISSUE TITLE
SM2解密 后台采用hutool，密文加了04，但是还是偶发解密不了，报错InvalidCipherTextException: invalid cipher text

### ISSUE THREAD

**Issue by pym15970914014** [JuneAndGreen/sm-crypto#98]
密文值：b89f48e4d80565fce37a16b95803e6b363e179110c237fc4f8d0c7fb0e29d93e7db2a7046e63d5c67dbd32b1a340806c48ca6722994253b7ff76dfd869bc5e7f7286341a1e8973de339701cb528b3643e478a4d46b6f232cb4352fc11c107ad3

**Comment by JuneAndGreen** [comment]
本库是按照这份文档实现的：https://github.com/JuneAndGreen/sm-crypto/blob/master/docs/SM2%E6%A4%AD%E5%9C%86%E6%9B%B2%E7%BA%BF%E5%85%AC%E9%92%A5%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95.pdf

使用其他工具时请对照是否一致。
