### ISSUE TITLE
IE 出现兼容问题，建议修改 packjson 的main的路径

### ISSUE THREAD

**Issue by JHCan333** [JuneAndGreen/sm-crypto#99]
![image](https://github.com/JuneAndGreen/sm-crypto/assets/44151872/53ace7c6-5e7a-4fb7-8eed-1e6b0af1f0ba)

建议修改 package.json 的 main 路径指向转码后的 dist，不然会出现IE浏览器的兼容问题

**Comment by JuneAndGreen** [comment]
不考虑兼容 ie。

你如果不想用 babel 过 src 的话，可以直接改 webpack 等构建工具取 dist 下的来用就行。
